# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: predictor.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'predictor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fpredictor.proto\x12\tpredictor\"l\n\x11PredictionRequest\x12\x0f\n\x07history\x18\x01 \x03(\x02\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x1a\n\x12sla_violation_rate\x18\x03 \x01(\x02\x12\x17\n\x0fwasted_capacity\x18\x04 \x01(\x02\"n\n\x12PredictionResponse\x12\x0c\n\x04mean\x18\x01 \x01(\x02\x12\x0f\n\x07std_dev\x18\x02 \x01(\x02\x12\x13\n\x0bupper_bound\x18\x03 \x01(\x02\x12\x13\n\x0blower_bound\x18\x04 \x01(\x02\x12\x0f\n\x07z_score\x18\x05 \x01(\x02\x32[\n\tPredictor\x12N\n\rGetPrediction\x12\x1c.predictor.PredictionRequest\x1a\x1d.predictor.PredictionResponse\"\x00\x42\x32Z0github.com/samarthsrao/capstone/protos/predictorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predictor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/samarthsrao/capstone/protos/predictor'
  _globals['_PREDICTIONREQUEST']._serialized_start=30
  _globals['_PREDICTIONREQUEST']._serialized_end=138
  _globals['_PREDICTIONRESPONSE']._serialized_start=140
  _globals['_PREDICTIONRESPONSE']._serialized_end=250
  _globals['_PREDICTOR']._serialized_start=252
  _globals['_PREDICTOR']._serialized_end=343
# @@protoc_insertion_point(module_scope)
