services:
  predictor:
    build:
      context: ./services/load-predictor
    ports:
      - "50051:50051"
    networks:
      - capstone-net

  orchestrator:
    build:
      context: ./services/orchestrator
    ports:
      - "8082:8082"
    depends_on:
      - predictor
    networks:
      - capstone-net

  dummy-ecommerce:
    build:
      context: ./services/dummy-ecommerce
    ports:
      - "8084:8084"
    depends_on:
      - orchestrator
    networks:
      - capstone-net

networks:
  capstone-net:
    driver: bridge
